# clk_in
set_property PACKAGE_PIN E3 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# switch
set_property PACKAGE_PIN V10 [get_ports switch[2]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[2]]
set_property PACKAGE_PIN U11 [get_ports switch[1]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[1]]
set_property PACKAGE_PIN U12 [get_ports switch[0]]
set_property IOSTANDARD LVCMOS33 [get_ports switch[0]]

#Int_button
set_property PACKAGE_PIN P17 [get_ports Int_button[0]]
set_property IOSTANDARD LVCMOS33 [get_ports Int_button[0]]
set_property PACKAGE_PIN N17 [get_ports Int_button[1]]
set_property IOSTANDARD LVCMOS33 [get_ports Int_button[1]]
set_property PACKAGE_PIN M17 [get_ports Int_button[2]]
set_property IOSTANDARD LVCMOS33 [get_ports Int_button[2]]

# enable
set_property PACKAGE_PIN U13 [get_ports enable[7]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[7]]
set_property PACKAGE_PIN K2 [get_ports enable[6]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[6]]
set_property PACKAGE_PIN T14 [get_ports enable[5]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[5]]
set_property PACKAGE_PIN P14 [get_ports enable[4]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[4]]
set_property PACKAGE_PIN J14 [get_ports enable[3]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[3]]
set_property PACKAGE_PIN T9 [get_ports enable[2]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[2]]
set_property PACKAGE_PIN J18 [get_ports enable[1]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[1]]
set_property PACKAGE_PIN J17 [get_ports enable[0]]
set_property IOSTANDARD LVCMOS33 [get_ports enable[0]]

# out
set_property PACKAGE_PIN T10 [get_ports out[7]]
set_property IOSTANDARD LVCMOS33 [get_ports out[7]]
set_property PACKAGE_PIN R10 [get_ports out[6]]
set_property IOSTANDARD LVCMOS33 [get_ports out[6]]
set_property PACKAGE_PIN K16 [get_ports out[5]]
set_property IOSTANDARD LVCMOS33 [get_ports out[5]]
set_property PACKAGE_PIN K13 [get_ports out[4]]
set_property IOSTANDARD LVCMOS33 [get_ports out[4]]
set_property PACKAGE_PIN P15 [get_ports out[3]]
set_property IOSTANDARD LVCMOS33 [get_ports out[3]]
set_property PACKAGE_PIN T11 [get_ports out[2]]
set_property IOSTANDARD LVCMOS33 [get_ports out[2]]
set_property PACKAGE_PIN L18 [get_ports out[1]]
set_property IOSTANDARD LVCMOS33 [get_ports out[1]]
set_property PACKAGE_PIN H15 [get_ports out[0]]
set_property IOSTANDARD LVCMOS33 [get_ports out[0]]
